import type {
  TradeCandidate,
  RegimeData,
  PortfolioData,
  SystemStatus,
} from "./types"

export const mockCandidates: TradeCandidate[] = [
  {
    ticker: "NVDA",
    strategy: "Bull Call Spread",
    dte: 5,
    growthScore: 0.74,
    elr: "+3.21%",
    pop: "71.4%",
    regimeStatus: "PASS",
    liquidity: 0.81,
    impact: "Low",
    allocation: "1.6%",
    riskAmount: "$164",
    rationale: "ELR positive after TCA · Regime stable · Liquidity sufficient",
    drivers: ["ELR: +3.21%", "Regime: 0.82", "Liq: 0.81"],
    status: "FIRE",
    audit: {
      costModel: {
        grossELR: "+4.18%",
        tcaDeduction: "-0.97%",
        netELR: "+3.21%",
      },
      popEstimate: {
        deltaProxy: "0.724",
        bucketHits: "—",
        ciLower: "0.651",
        confidence: "Low (Phase 1 proxy)",
      },
      kellySizing: {
        kellyRaw: "0.061",
        halfKelly: "0.031",
        finalCapped: "0.016",
        dollarRisk: "$164",
      },
      gateResults: [
        { label: "ELR > 0 (after TCA)", passed: true },
        { label: "Regime Score > 0.4", passed: true },
        { label: "Liquidity Score > 0.5", passed: true },
        { label: "Drawdown Multiplier > 0", passed: true },
        { label: "Growth Score > 0.3", passed: true },
        { label: "Trades today < 3", passed: true },
        { label: "Portfolio risk < 6%", passed: true },
        { label: "No correlated duplicate", passed: true },
      ],
      timestamp: "Evaluated 09:47:03 AM ET",
    },
  },
  {
    ticker: "AAPL",
    strategy: "Bull Call Spread",
    dte: 7,
    growthScore: 0.44,
    elr: "+1.12%",
    pop: "64.2%",
    regimeStatus: "PASS",
    liquidity: 0.61,
    impact: "Medium",
    allocation: null,
    riskAmount: null,
    rationale: "Growth score below threshold · Monitoring for improvement",
    drivers: ["ELR: +1.12%", "Regime: 0.76", "Liq: 0.61"],
    status: "WATCH",
    audit: null,
  },
  {
    ticker: "TSLA",
    strategy: "Bear Put Spread",
    dte: 4,
    growthScore: 0.0,
    elr: null,
    pop: null,
    regimeStatus: "BLOCK",
    liquidity: 0.38,
    impact: "High",
    allocation: null,
    riskAmount: null,
    rationale: "Regime blocked · Liquidity below threshold",
    drivers: ["Regime: BLOCK", "Liq: 0.38", "Impact: High"],
    status: "BLOCK",
    audit: null,
  },
]

export const mockRegime: RegimeData = {
  indicators: [
    { label: "VIX", value: "18.4", status: "green" },
    { label: "IV/HV Ratio", value: "1.34", status: "green" },
    { label: "SPY vs 200d EMA", value: "Above", status: "green" },
    { label: "VIX 24h Change", value: "+2.1%", status: "yellow" },
    { label: "Last Econ Event", value: "3.2h · CPI", status: "green" },
  ],
  score: 0.78,
  status: "PASS",
}

export const mockPortfolio: PortfolioData = {
  balance: "$10,247.30",
  dayPnl: "+$142.80",
  dayPnlPositive: true,
  openPositions: 1,
  openRisk: 1.6,
  maxRisk: 6.0,
  weeklyDrawdown: 4.2,
  maxDrawdown: 15.0,
  tradesToday: 1,
  maxTrades: 3,
  swarmActive: true,
  swarmMode: "Running · Half-Kelly · Paper Mode",
}

export const mockSystemStatus: SystemStatus = {
  lastScan: "09:47 AM ET",
  nextScan: "10:17 AM ET",
  evaluated: 3,
  fireCount: 1,
  watchCount: 1,
  blockCount: 1,
  noTradeReason: null,
}
